CREATE TABLE STATE (
STATE_ID SERIAL PRIMARY KEY,
NAME TEXT  );

CREATE TABLE COLOR (
COLOR_ID SERIAL PRIMARY KEY, 
NAME TEXT  );

CREATE TABLE TEAM (
TEAM_ID SERIAL PRIMARY KEY  , 
NAME TEXT  ,
STATE_ID INT, 
COLOR_ID INT, 
WINS INT, 
LOSSES INT,
FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE);

CREATE TABLE PLAYER (   
PLAYER_ID SERIAL PRIMARY KEY  ,   
TEAM_ID INT  ,    
UNIFORM_NUM INT  ,   
FIRST_NAME TEXT  ,    
LAST_NAME TEXT  ,     
MPG INT ,    
PPG INT ,    
RPG INT ,    
APG INT,    
SPG NUMERIC(2,1) ,   
BPG NUMERIC(2,1) ,
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE); 

