# Generated by Django 4.0.1 on 2022-03-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Team_id',
            new_name='team_id',
        ),
    ]
